/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Nervos CKB",
  "tagline": "Nervos CKB",
  "url": "https://docs.nervos.org",
  "baseUrl": "/",
  "organizationName": "nervosnetwork",
  "projectName": "docs-new",
  "scripts": [
    "/js/extra.js",
    "/js/scrollSidebar.js"
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "favicon": "img/favicon.png",
  "customFields": {
    "oldDocSiteUrl": "https://docs-old.nervos.org",
    "gaGtag": true,
    "disableHeaderTitle": true,
    "socialLinks": [
      {
        "label": "Twitter",
        "icon": "img/footer_twitter.png",
        "url": "https://twitter.com/nervosnetwork"
      },
      {
        "label": "Blog",
        "icon": "img/footer_medium.png",
        "url": "https://medium.com/nervosnetwork"
      },
      {
        "label": "Telegram",
        "icon": "img/footer_telegram.png",
        "url": "https://t.me/nervosnetwork"
      },
      {
        "label": "Reddit",
        "icon": "img/footer_reddit.png",
        "url": "https://www.reddit.com/r/NervosNetwork/"
      },
      {
        "label": "YouTube",
        "icon": "img/footer_youtube.png",
        "url": "https://www.youtube.com/channel/UCONuJGdMzUY0Y6jrPBOzH7A"
      },
      {
        "label": "Forum",
        "icon": "img/footer_forum.png",
        "url": "https://talk.nervos.org/"
      }
    ]
  },
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "gtag": {
          "trackingID": "G-Q42TXTFP46",
          "anonymizeIP": true
        },
        "docs": {
          "path": "./docs",
          "breadcrumbs": false,
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": false,
          "sidebarPath": "/Users/sss/Desktop/docs.nervos/website/sidebars.js",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "editUrl": "https://github.com/nervosnetwork/docs-new/tree/develop/website"
        },
        "blog": {
          "path": "blog",
          "editLocalizedFiles": false,
          "blogTitle": "Nervos Blog",
          "blogDescription": "Blog Posts About Nervos Blockchain",
          "blogSidebarCount": 20,
          "blogSidebarTitle": "All Posts",
          "routeBasePath": "blog",
          "include": [
            "**/*.{md,mdx}"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ],
          "postsPerPage": 1,
          "blogListComponent": "@theme/BlogListPage",
          "blogPostComponent": "@theme/BlogPostPage",
          "blogTagsListComponent": "@theme/BlogTagsListPage",
          "blogTagsPostsComponent": "@theme/BlogTagsPostsPage",
          "truncateMarker": {},
          "showReadingTime": true,
          "feedOptions": {
            "title": "Nervos Blog",
            "description": "Blog Posts About Nervos Blockchain"
          }
        },
        "theme": {
          "customCss": [
            "/Users/sss/Desktop/docs.nervos/website/src/css/customTheme.css"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "/Users/sss/Desktop/docs.nervos/website/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
      {}
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "from": "/docs",
            "to": "/"
          },
          {
            "from": "/docs/reference/rpc/",
            "to": "/docs/node/rpcs"
          },
          {
            "from": "/docs/reference/tools",
            "to": "/docs/sdk-and-devtool/devtool"
          },
          {
            "from": "/docs/basics/concepts/economics",
            "to": "/docs/tech-explanation/economics"
          },
          {
            "from": "/docs/basics/glossary/",
            "to": "/docs/tech-explanation/glossary"
          },
          {
            "from": "/docs/basics/guides/mainnet",
            "to": "/docs/node/run-mainnet-node"
          },
          {
            "from": "/docs/basics/guides/get-ckb",
            "to": "https://docs-old.nervos.org/docs/basics/guides/get-ckb"
          },
          {
            "from": "/docs/basics/guides/mining-ckb",
            "to": "/docs/mining/guide"
          },
          {
            "from": "/docs/reference/halving",
            "to": "/docs/mining/halving"
          },
          {
            "from": [
              "/docs/basics/guides/crypto wallets/neuron",
              "/docs/basics/guides/neuron"
            ],
            "to": "https://docs-old.nervos.org/docs/basics/guides/crypto wallets/neuron"
          },
          {
            "from": "/docs/basics/tools",
            "to": "https://docs-old.nervos.org/docs/basics/tools"
          }
        ]
      }
    ],
    null
  ],
  "themeConfig": {
    "prism": {
      "additionalLanguages": [
        "bash",
        "powershell",
        "rust",
        "json"
      ],
      "theme": {
        "plain": {
          "color": "var(--code-plain)",
          "backgroundColor": "var(--surface-02)"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          },
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "var(--code-comment)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "var(--code-constant)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "var(--text-secondary)"
            }
          },
          {
            "types": [
              "function",
              "attr-name"
            ],
            "style": {
              "color": "var(--code-function)"
            }
          },
          {
            "types": [
              "keyword",
              "attr-value"
            ],
            "style": {
              "color": "var(--code-keyword)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "var(--code-plain)",
          "backgroundColor": "var(--surface-02)"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "var(--code-comment)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "var(--text-secondary)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "var(--code-constant)"
            }
          },
          {
            "types": [
              "function",
              "attr-name"
            ],
            "style": {
              "color": "var(--code-function)"
            }
          },
          {
            "types": [
              "keyword",
              "attr-value"
            ],
            "style": {
              "color": "var(--code-keyword)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "src": "img/logo-dark.png",
        "width": 89,
        "height": 32,
        "alt": "Nervos CKB Docs",
        "href": "/"
      },
      "items": [
        {
          "to": "/docs/getting-started/how-ckb-works",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "type": "search",
          "position": "right",
          "className": "navbar-search"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<a class=\"help-flex\" href=\"https://discord.gg/4Jcw8MwEEv\" target=\"__blank\"><img alt=\"Discord for help\" src=\"/svg/icon-discord.svg\" width={24} height={24}><p class=\"help-text\">Get Help</p></a>",
          "className": "navbar-help"
        }
      ],
      "hideOnScroll": false
    },
    "algolia": {
      "appId": "LU9B8PQ7W5",
      "apiKey": "122c7efa6c0425cfd6852286c746e653",
      "indexName": "nervos",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
